### ISSUE TITLE
How to get the pia key

### ISSUE THREAD

**Issue by Lekuruu** [kinnay/NintendoClients#100]
Hi, I am currently trying to find the pia key for splatoon 3 in a disassembler. Does anyone know how to do that, or if there is a list of all keys that I could use?

Thanks in advance!

**Comment by kinnay** [comment]
Pia packets are encrypted with the session key, which depends on the network type (NPLN, LDN or LAN). See [Pia Protocol](https://github.com/kinnay/NintendoClients/wiki/Pia-Protocol). This is not the same as the game key, although the game key may be used to generate the session key.

There is not one specific way to find the game key, because it really depends on how the game is implemented. Some games simply store it as a string, while others use a RNG with a fixed seed to generate the key. There is a table [here](https://github.com/kinnay/NintendoClients/wiki/Pia-Game-Keys), but it is very incomplete.

**Comment by Lekuruu** [comment]
Yeah I have realized that a bit too late with the session key. Anyways, @0raffy0 may have found a game key in memory, but my session key implementation is probably wrong...

Here it is: `78deee82d86875782c40b15278f37815`

**Comment by Lekuruu** [comment]
I will close this issue for now

**Comment by Lekuruu** [comment]
If you could write an example function that creates the session key, I would appreciate it!

**Comment by 0raffy0** [comment]
So...
I'm the second guy that wants to decrypt the packet with Lekuru.
Basically our situation is that we have a bunch of packets and the game specific key.
The packets are those attached to this message (it could be obvious to you but you have to open them with Wireshark). And the game specific key is this: 
78deee82d86875782c40b15278f37815 (I'm sure at 99.99% this is the right Lan specific key) 
We rode your documentation about the packet structure but we still have some troubles in decrypting them. Are the info that we have enough to decrypt the packets or do we still need something? If we don't, could you tell us the process to decrypt the packet? 
Thanks in advice!

**Comment by kinnay** [comment]
@Lekuruu Sorry, I won't be writing any code for you. The information is on the wiki, so you should be able to do it yourself. However, I may be able to tell you what's wrong if you show me your code. Also, I haven't really looked into Pia 6.x. It's possible that they changed the algorithm.

@0raffy0 This looks like LAN mode. Unless Nintendo changed something, all you need to generate the session key are the [browse reply](https://github.com/kinnay/NintendoClients/wiki/LAN-Protocol#1-browse-reply), which is the third packet in your pcap, and the game-specific key. I think that you have enough information.

**Comment by Lekuruu** [comment]
@kinnay Thanks for your reply and sorry if we annoyed you. It seems like Pia 6.25 has changed the browse request/reply quite a bit, but the session param should still be in the last 32 bytes. We will look into this ourselves now.
