### ISSUE TITLE
How to dump switchShop certificate?

### ISSUE THREAD

**Issue by erew70** [kinnay/NintendoClients#135]
hello, i am trying to proxy traffic with charles and was wondering how do you obtain the certificate? i heard you need to extract it from libappshop NSO but idk can someone help me please? Thank you

**Comment by kinnay** [comment]
There are two different certificates:
* The SwitchShop certificate, which is used for https://bugyo.hac.lp1.eshop.nintendo.net
* The device certificate, which is used for other servers.

Here is a guide that explains how to dump the certificates: https://gist.github.com/InternalLoss/363356b26e3cb45d680d08ac99e8ff6d

The SwitchShop certificate is indeed stored in the LibAppletShop NSO. Try opening it in IDA. In the 18.1.0 version, you will find the certificate at `0x7100961C29`.  You can also try searching for the bytes `30 82 0A F1` in IDA to find it.

**Comment by jonbarrow** [comment]
> Here is a guide that explains how to dump the certificates: [gist.github.com/InternalLoss/363356b26e3cb45d680d08ac99e8ff6d](https://gist.github.com/InternalLoss/363356b26e3cb45d680d08ac99e8ff6d)

I'll contact Billy on Discord about this, but it should be noted that this guide is a bit outdated and the links to the lockpick repos are no longer available due to the DMCA takedowns a while ago. So this guide alone is not enough for what @erew70 wants to do

(also they did know about this guide already, they commented on it a week ago)

**Comment by kinnay** [comment]
You can use Ghidra if you don't want to use IDA.

Not sure what's the easiest way to dump the applet. Personally, I'm using the example script from this repo to download a system update, and hactool to unpack it.

And NXCA2Prod10 is not the name of the SwitchShop certificate. NXCA2Prod10 sounds more like the device certificate.

Also, proxying the eshop will not help you with unbanning your Switch in any way...

**Comment by kinnay** [comment]
Yes, Ghidra is free. You can download it here: https://ghidra-sre.org/. You will also have to find a plugin for it for loading NSO files.

Alternatively, if you just want to extract the certificate, you could try looking up the NSO file format on switchbrew, and decompress the sections manually.

Where did you hear about NintendoNXCA2Prod10? The device certificate is issued by NintendoNXCA2Prod1. The SwitchShop certificate has nothing to do with that though. SwitchShop is issued by Nintendo CA - G3.

**Comment by kinnay** [comment]
Ah I see what you mean. That '0' at the end of not part of the name actually. The '0' is there because of the way that certificates are encoded. This tool visualizes it quite well: https://lapo.it/asn1js/. It's really just `NXCA2Prod1`.

You can use [hactool](https://github.com/SciresM/hactool/) to unpack the NCA. Something like this should work:
* `hactool -t nca --exefsdir=exefs <hash.nca>`

You will have to place prod.keys in the right location for it work. See 'External Keys' in the hactool README.

**Comment by kinnay** [comment]
> Also if NXCA2Prod1 is used for authentication then what is NX Prod 1 for?

NX Prod 1 is the device certificate. This one is stored on your Switch, and can be dumped.

NXCA2Prod1 is the certificate authority. The authority is a certificate that is used by Nintendo to sign and verify device certificates. No one outside of Nintendo has access to it.

> i searched for bytes and everything and nothing shows up. can you help please?

If you correctly loaded the NSO into Ghidra, then searching for the bytes that I mentioned should bring you to the certificate. Maybe people on the Reswitched discord are able to help you more: https://discordapp.com/invite/ZdqEhed

**Comment by kinnay** [comment]
Can we talk elsewhere? My discord is yannik9647.

I'm going to close this because issues are not meant for this kind of user support.
