### ISSUE TITLE
Use MM2 example without a digital download

### ISSUE THREAD

**Issue by TheGreatRambler** [kinnay/NintendoClients#26]
I noticed that the MM2 example only uses the ticket in one place:
```python
response = aauth.auth_digital(
	SMM2.TITLE_ID, SMM2.TITLE_VERSION,
	device_token, ticket
)
```
Is there an equivalent `aauth.auth_gamecard` to use with game cards? Thank you

**Comment by Kinnay** [comment]
This is not possible at the moment, but it's definitely something I'd like to support. Unfortunately, I'm not sure if I can do it on my own.

Game card authentication involves some kind of challenge which is calculated by the ChallengeCardExistence command. This command seems to use the Gamecard ASIC internally though, which makes it difficult for me to figure out how it works.

If someone knows how ChallengeCardExistence works I can add this feature to NintendoClients, but until then you won't be able to use a game card I'm afraid :(

**Comment by TheGreatRambler** [comment]
Disappointing but understood.

**Comment by TheGreatRambler** [comment]
Wait, can you use a ticket that has had the console specific info removed from it from nxdumptool?

**Comment by Kinnay** [comment]
Probably not. I wouldn't try it, because it will probably get your Switch banned.

By the way, if you don't mind I'll keep this issue open to remind me to research this more when I have time.

**Comment by TheGreatRambler** [comment]
Great! I tried with a ticket scrubbed of console specific data and it seems to be refused. I'm not gonna try again in fear of getting banned

**Comment by ThatNerdyPikachu** [comment]
> Great! I tried with a ticket scrubbed of console specific data and it seems to be refused. I'm not gonna try again in fear of getting banned

Uh oh... you're definitely getting banned.
Sorry.

Maybe not now, but some time in the future. (They ban in waves, so once you get flagged (which you likely were), you get banned in the next wave)

**Comment by TheGreatRambler** [comment]
There's any number of things I could have gotten wrong in the request besides a scrubbed ticket, so I'm holding out hope :)

**Comment by TheGreatRambler** [comment]
I'm still interested on this subject. I might be banned, but I still want to pursue this. I'm afraid I just don't know how to reverse engineer...

**Comment by iomintz** [comment]
Maybe a small bit of homebrew could be written which obtains an aauth and dauth token and writes them to SD?

**Comment by TheGreatRambler** [comment]
I would be a fan of that idea. In fact, I would be willing to develop it if that idea is considered.

**Comment by iomintz** [comment]
It's not great as the tokens only last 24h. The homebrew could be taken one step further by running as a sysmodule, listening on a socket, and responding with a new aauth/dauth token whenever requested. I'm imagining someone setting up a REST API that uses a real Nintendo Switch as part of the backend lol

**Comment by TheGreatRambler** [comment]
From the requirements of this repo, it seems as if everything required can be dumped from a real Nintendo Switch once and never again. Tokens are generated according to that data. Those files could be dumped once by an applet.

**Comment by TheGreatRambler** [comment]
In fact, my reason for creating this issue is I do want to create a REST API for certain MM2 requests. For the TAS community specifically.

**Comment by iomintz** [comment]
> From the requirements of this repo, it seems as if everything required can be dumped from a real Nintendo Switch once and never again. Tokens are generated according to that data. Those files could be dumped once by an applet.

What data? Temporary tokens are generated from a ticket. Unless we can RE gamecard auth, tokens would have to be generated on real hardware once every 24h.

**Comment by Kinnay** [comment]
I feel like there's some confusion here. I'll try to make it clear:

* An aauth token is required to connect to a game server. This allows Nintendo to verify that you really bought the game.
* An aauth token can **not** be permanently dumped. Your Switch requests a new token from the aauth server every time you go online in a game. An aauth token is only valid for 24 hours. After that it can no longer be used.
* Like a real Switch, my example scripts request a new aauth token every time you run them. However, I have only been able to implement this for digital titles.
* If you can obtain an aauth token for game cards through other means then you **can** use it to connect to game servers with NintendoClients. For example, you could write a homebrew application that request an aauth token on a real Switch. However, it is not permanent as the token is only valid for 24 hours, i.e. you will have to run the homebrew application again after 24 hours.

It would be best if NintendoClients could request an aauth token for game cards on its own (using only permanently dumped files), so that you could write scripts with NintendoClients without running a homebrew app on your Switch every day.

I'm pretty sure that the part that I'm missing is done by the Lotus firmware. It is encrypted though, and no one has been able to get the keys as far as I know. That's why NintendoClients can't automatically request an aauth token for game cards at the moment.

**Comment by Kinnay** [comment]
Btw if you know how to set up a mitm on your Switch you can already get an aauth token for game cards without writing a new homebrew application: just intercept the aauth request while going online in a game.

**Comment by TheGreatRambler** [comment]
Could you give me a quick lowdown on how to intercept aauth tokens? I tried to do so with Wireshark and http mitm but was unsuccessful. I would gladly make a quick applet for that.

**Comment by iomintz** [comment]
https://github.com/misson20000/exefs_patches/tree/master/atmosphere/exefs_patches/disable_ca_verification
install this by copying the folder to atmosphere/exefs_patches

set up your proxy's HTTP host and port in stock switch network settings. If you're using WiFi, you can make another profile for proxying if you need. Connect.

**Comment by TheGreatRambler** [comment]
I got mitmproxy and put my computers ip address in the proxy ip and the proxy port provided by mitmproxy, but I couldn't log into the eshop. Do the provided patches only apply to applications?

**Comment by TheGreatRambler** [comment]
Okay, just wanted to test the proxy in a less destructive place.

**Comment by Kinnay** [comment]
You probably need the `disable_browser_ca_verification` patch in addition to the normal `disable_ca_verification` patch. I never tried to mitm the eshop myself, but I don't see why it shouldn't work.
