### ISSUE TITLE
Super smash bros ultimate

### ISSUE THREAD

**Issue by Jpizzle974** [kinnay/NintendoClients#52]

**Comment by Kinnay** [comment]
I've never played this game. I think it would be nice to learn more about it though. It should be possible to connect to the server and call methods already, but the server probably also provides a few custom methods. The game server id and access key are documented [here](https://github.com/Kinnay/NintendoClients/wiki/Game-Server-List).

**Comment by kinnay** [comment]
It is difficult to figure out more about SSBU because the game provides very little debugging information. I don't think it is worth the time for me to reverse engineer all methods of this game. If someone else wants to try, I would be happy to accept a PR though.

I'm closing this issue for this reason. And also because there is no clear goal in this issue. If I should reopen it, let me know.
