### ISSUE TITLE
<message>Unlinked device</message>

### ISSUE THREAD

**Issue by zecoxao** [kinnay/NintendoClients#75]
i get Unlinked device when using donkey kong client. does anybody know why this happens?

INFO:anynet.http:Received HTTP response: 400
ERROR:nintendo.nnas:Account request returned status code 400
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<errors>
    <error>
        <code>0110</code>
        <message>Unlinked device</message>
    </error>
</errors>

**Comment by kinnay** [comment]
You must provide a valid device id and serial number at the top of the script, and they must belong to a Wii U that is linked to your NNID (which you must also provide at the top of the script). If you believe that you filled in all parameters correctly, check if you made any typos. Also make sure that you are using the correct format (i.e. provide the device id as an integer; a hex string will not work).

**Comment by zecoxao** [comment]
ah, ok, that's the issue. i'm using a 3ds serial number and device id, which is why it doesn't work with the wii u script.
thanks. you may close the issue :)
a question though, will there ever be support for 3ds?

**Comment by kinnay** [comment]
Probably not. The Switch is much more interesting in my opinion because it is newer.

**Comment by kinnay** [comment]
I mean, I'm not against adding 3DS support, but someone else would have to figure out how its servers work. I'm currently only researching Switch servers whenever I have time.

My NEX implementation (i.e. game servers) actually supports 3DS servers. The problem is that I never tried to figure out how the 3DS obtains NEX credentials from the account server.
